---  # https://docs.ansible.com/ansible/latest/collections/community/aws/iam_module.html
- name: Add AWS IAM user
  hosts: localhost
  become: true
  become_method: sudo
  tasks: 
  - name: Install package
    ansible.builtin.package: 
      name: telnet
      state: present