--- # https://docs.ansible.com/ansible/latest/collections/community/aws/iam_module.html
- name: Add AWS IAM user
  hosts: localhost
  vars_files:
    envs/dev.yaml
  tasks:
  - name: Create two new IAM users with API keys
    community.aws.iam:
      iam_type: user
      name: "{{ item }}"
      state: present
      password: "{{ password }}"
      access_key_state: "{{ access_key_state }}"
    loop: "{{ list_of_users }}"



  - name: Create Groups
    community.aws.iam:
      iam_type: group
      name: "{{ item }}"
      state: present
    loop: "{{ list_of_groups }}"
    register: new_groups
