---
- name: ansible IAAC
  hosts: localhost
  tasks:
  - name: create a VPC
    amazon.aws.ec2_vpc_net:
      name: Ansible
      cidr_block: 10.0.0.0/16
      region: us-east-1
      state: present
      tags:
        module: ec2_vpc_net
        this: works
      tenancy: default